name: 下載並解壓縮工件

on:
  workflow_run:
    workflows: ["壓縮並上傳為工件"]
    types:
      - completed

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: 下載工件
        uses: actions/download-artifact@v3
        with:
          name: compressed-files

      - name: 解壓縮檔案
        run: |
          tar -xzf compressed-files/files.tar.gz -C extracted  # 解壓縮到指定目錄

      - name: 列出檔案
        run: |
          ls -R extracted  # 列出解壓縮後的檔案
