# @format

name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use API Key
        run: echo "The API key is ${{ secrets.API_KEY }}"
        env:
          API_KEY: ${{ secrets.API_KEY }}
