name: 建立 PR

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發工作流程

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出代碼
        uses: actions/checkout@v2

      - name: 設置 Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 安裝 GitHub CLI
        run: sudo apt-get install gh

      - name: 創建新分支並進行變更
        run: |
          git checkout -b update-branch
          echo "// Code change made by GitHub Actions" >> file.txt
          git add file.txt
          git commit -m "Automated commit by GitHub Actions"

      - name: 推送變更並創建 Pull Request
        run: |
          git push origin update-branch
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh pr create --title "Automated PR" --body "This is an automated PR created by GitHub Actions" --base main --head update-branch
