name: "Sync GitHub Issues to Notion"
description: "Synchronize GitHub issues to a Notion database"
inputs:
  repo:
    description: "The GitHub repository (e.g., owner/repo)"
    required: true
  NOTION_API_KEY:
    description: "The API key for the Notion integration"
    required: true
  NOTION_DATABASE_ID:
    description: "The ID of the Notion database"
    required: true
runs:
  using: "node12"
  steps:
    - name: Run script
      uses: actions/setup-node@v3
      with:
        node-version: "20"
    - run: npm install
    - run: node script.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NOTION_API_KEY: ${{ inputs.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ inputs.NOTION_DATABASE_ID }}
